name: Convert to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.7.0

    - name: Customize styles
      run: |
        echo "<style>* { font-family: 'Arial', sans-serif; }</style>" >> style.css
        cat README.md >> styled_readme.md

    - name: Convert to PDF
      uses: docker://pandoc/latex:2.13
      with:
        args: "styled_readme.md -o output.pdf --template=eisvogel --listings --css=style.css"

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-artifact
        path: output.pdf
